#!/bin/sh

set -e

set -o pipefail && xcodebuild \
-workspace Example/SSAccessibility.xcworkspace \
-scheme SSAccessibility \
-sdk iphonesimulator \
-destination "platform=iOS Simulator,name=iPhone Retina (4-inch 64-bit)" \
clean test \
ONLY_ACTIVE_ARCH=NO \
RUN_CLANG_STATIC_ANALYZER=YES \
CLANG_STATIC_ANALYZER_MODE=deep | xcpretty -c
