#!/bin/sh

set -e

cd Example
pod install

xctool \
-workspace SSAccessibility.xcworkspace \
-scheme SSAccessibility \
-sdk iphonesimulator \
build \
ONLY_ACTIVE_ARCH=NO \
RUN_CLANG_STATIC_ANALYZER=YES \
CLANG_STATIC_ANALYZER_MODE=deep
